spring.application.name=adapt-learn


# Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:adapt_learn}}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Security
jwt.secret=${JWT_SECRET:change_this_to_a_secure_random_string_in_production}
jwt.expiration=${JWT_EXPIRATION:86400000}