spring.application.name=adapt-learn


# Database Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/adapt_learn}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root123}

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Security
jwt.secret=3b0a3c067c3df78e3f7dcf5fdd114ecbbfd9781fe3b7a3ac8b4716586cf8d099
jwt.expiration=${JWT_EXPIRATION:86400000}